spring.application.name=coderestapi
# Para um banco local (porta padrão 27017)
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=nome_do_seu_banco
#spring.data.mongodb.uri=mongodb://localhost:27017/nome_do_seu_banco

